name: Upload Artifact
on: 
    push:
        branches:
            - main
jobs:
    job-1:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: get sources
              uses: actions/checkout@v4
            - run: npm install
            - run: npm run test
            - run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                name: mon-site
                path: ./dist/
    job-2:
        name: list-artefact
        needs: job-1
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: mon-site
                path: .
            - run: ls mon-site
        
